### PR TITLE
[HOPS-61] Block Management Refactoring

### PR DESCRIPTION
**Pull request by augustbonds**

### CODE REVIEW

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by kouzant** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Pull request closed without merging**
