### PR TITLE
[Hops 819] Close leader NN and other namenode proxies in DFSClient.close

### PR DESCRIPTION
**Pull request by smkniazi**
## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-819

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by berthoug** [comment]
How are the modifications to BPOfferService.java, BPServiceActor.java and TestHAFileCreation.java related to the Jira?
And @maismail  created another pull request for exactly the same bug. It looks to me like @maismail  forgot something in his solution, can you confirm that it is the case and that I should take yours instead of his (#573)?

**Comment by smkniazi** [comment]
They not directly related. While fixing the client I found a race condition in the datanode classes which was causing unnecessary delays in our HA tests that I was using to test the client changes

**Comment by berthoug** [comment]
Then do two different JIRAs and pull requests.
And have you looked at @maismail  pull request?

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
This break org.apache.hadoop.hdfs.TestDFSClientRetries.

**Comment by smkniazi** [comment]
Updated the code accordingly

**Comment by berthoug** [comment]
Jenkins test this please.

**Pull request merged**
