### PR TITLE
OSX

### PR DESCRIPTION
**Pull request by bcleenders**
The changes I had to do to build Hops on OSX.

The first commit has the patch discussed here: https://issues.apache.org/jira/browse/HADOOP-10699

The second commit fixes an unknown constant.

Besides these changes, OSX users also have to do the following:

```
# Install protobuf 2.5 (protobuf 2.6 is too new)
brew install protobuf250

# Cmake is not automatically installed on OSX, apparently
brew install cmake
```

And, if you run JDK 7 (probably also for 8 and above), you have to symlink tools.jar:
```
# Find your installation folder by doing `which java`
cd /Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home/
sudo mkdir Classes && cd Classes
sudo ln -s ../jre/lib/rt.jar classes.jar
# See also https://issues.apache.org/jira/secure/attachment/12602452/HADOOP-9350.patch
```

### CODE REVIEW

**Comment by jimdowling** [comment]
test this please

**Comment by berthoug** [comment]
Jenkins retest this please

**Comment by berthoug** [comment]
Jenkins retest this please

**Comment by berthoug** [comment]
Jenkins retest this please

**Comment by berthoug** [comment]
Jenkins retest this please

**Comment by berthoug** [comment]
Jenkins retest this please

**Comment by berthoug** [comment]
Jenkins retest this please

**Pull request merged**
