### PR TITLE
[HOPS-677] Parallelize -copyFromLocal

### PR DESCRIPTION
**Pull request by smkniazi**
## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-677

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
performance improvement

* **What is the new behavior (if this is a feature change)?**
faster

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no
* **Other information**:

### CODE REVIEW

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
A bunch of test get a NullPointerException in the new code.

**Comment by smkniazi** [comment]
updated

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
There is still a lot of test failing.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by kouzant** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Command.processPaths is used in a lot of function, one of them being LS, so the comments saying things like "go through all files first and copy them" are incorrect. Moreover, we can't have an LS function that returns results in a random order, especially given that the ls function has options to specify the order in which we want the results to be displayed (cf broken TestHDFSCLI test).
I think we should either have an implementation that allows us to have some commands running sequentially and some commands in parallel or have a system to sort the returned values at the end of the process.

**Pull request merged**
