### PR TITLE
[HOPS-1318] fixing compatibility with hdfs-mount

### PR DESCRIPTION
**Pull request by smkniazi**
## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1318

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
How is increasing the id solving the problem?

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by smkniazi** [comment]
> How is increasing the id solving the problem?

no conflicting variables with same IDs

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Does that mean that hdfs-mount is adding its own variable to the protocol buffers?
If yes, could you add these variables as comments so that we can see what it is when reading the code?

**Comment by smkniazi** [comment]
> Does that mean that hdfs-mount is adding its own variable to the protocol buffers?
> If yes, could you add these variables as comments so that we can see what it is when reading the code?

hdfs-mount uses protocol definitions from hdfs.2.7.4. some of the variable IDs in hdfs-2.7.4 conflict with variable IDs in hopsfs. For example for create file request in hdfs  variable 8 is CryptoProtocolVersionProto cryptoProtocolVersion = 8; 
while variable 8 in hopsfs is
EncodingPolicyProto policy = 8;

**Comment by berthoug** [comment]
Ok.
Can you put the info as comments in the code so that nobody comes and change back the id, later on, thinking that it was a mistake.

**Comment by smkniazi** [comment]
done

**Pull request merged**
