### PR TITLE
[HOPS-1549] Do not set appId for WebHDFS x509 authentication

### PR DESCRIPTION
**Pull request by tkakantousis**
## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-1549

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Check JIRA description

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:
https://bbc1.sics.se/jenkins/job/hops-pull/432/

### CODE REVIEW

**Comment by tkakantousis** [comment]
> Can you write a unit test similar to this https://github.com/hopshadoop/hops/blob/master/hadoop-hdfs-project/hadoop-hdfs/src/test/java/io/hops/security/TestWebHDFSHopsTLS.java#L117 to capture this behaviour?

Done

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by tkakantousis** [comment]
Jenkins test this please.

**Comment by kouzant** [comment]
Jenkins test this please

**Pull request merged**
