### PR TITLE
[HOPS-1154] Clean code for block hash undo in file append and update …

### PR DESCRIPTION
**Pull request by smkniazi**
…pipe line RPCs

## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-1154

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
code more readable and it is closer to the algorithm publish in the paper

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Can you put a proper description in the jira?

**Comment by smkniazi** [comment]
fxied

**Comment by berthoug** [comment]
Jenkins test this please.

**Pull request merged**
