### PR TITLE
resolving foreign key exception when application attempt is completed

### PR DESCRIPTION
**Pull request by berthoug**
Correcting the foreign key exception that sometime happen when an application attempt finish. This foreign key exception was due to the fact that as the application attempt is updated before to be removed and the commit to the database was trying to do the update once the remove was committed.

Solving #55

### CODE REVIEW

**Comment by maismail** [comment]
Jenkins retest this please.

**Comment by berthoug** [comment]
Jenkins retest this please.

**Comment by berthoug** [comment]
Jenkins retest this please.

**Comment by berthoug** [comment]
This modifications have also been done by another branch they are now useless

**Pull request closed without merging**
