### PR TITLE
Heterogeneous storage

### PR DESCRIPTION
**Pull request by bcleenders**
Bram's stuff :)

Using this PR to keep track of the progress and post any comments...

Will post intermediate test results here, to show progress.

**This branch is used as history for other branches (like bcleenders/mover), so don't squash unless all other branches are first merged into this branch!**

### CODE REVIEW

**Comment by bcleenders** [comment]
So, the test results (just before the merge; commit 32c1a09) are:

```
Results :

Failed tests: 
  TestMissingBlocksAlert.testMissingBlocksAlert:117 expected:<2> but was:<4>
  TestDFSClientRetries.testNamenodeRestart:811->namenodeRestartTest:954->assertEmpty:1032 There are 1 exception(s):
  Exception 0: java.lang.RuntimeException: io.hops.exception.StorageException: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1245)
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1238)
	at org.apache.hadoop.security.UserGroupInformation.createRemoteUser(UserGroupInformation.java:1109)
	at org.apache.hadoop.security.UserGroupInformation.createUserForTesting(UserGroupInformation.java:1260)
	at org.apache.hadoop.hdfs.TestDFSClientRetries.createFsWithDifferentUsername(TestDFSClientRetries.java:1041)
	at org.apache.hadoop.hdfs.TestDFSClientRetries.access$100(TestDFSClientRetries.java:97)
	at org.apache.hadoop.hdfs.TestDFSClientRetries$6.run(TestDFSClientRetries.java:921)
	at java.lang.Thread.run(Thread.java:745)
  ... etc.

  TestOverReplicatedBlocks.testChooseReplicaToDelete:219 Replicas on node 92bb92d7-cc33-4765-8db6-2404633eb3cb should have been deleted expected:<4> but was:<2>
  TestComputeInvalidateWork.testCompInvalidate:75 expected:<3000> but was:<0>
  TestReplicationPolicy.testChooseTarget6:480 expected:<1> but was:<2>
  TestReplicationPolicy.testChooseTargetWithStaleNodes:599 expected:<127.0.0.1:12173[DISK]DS-e0679531-7c26-41e5-9d87-bafe49ac4cb2:NORMAL> but was:<127.0.0.1:26716[DISK]DS-73232afc-3adf-4a1e-ac1a-68af240ac473:NORMAL>
  TestReplicationPolicy.testChooseTargetWithHalfStaleNodes:638 null
  TestReplicationPolicy.testChooseTargetWithMoreThanHalfStaleNodes:696 expected:<0> but was:<2>
  TestReplicationPolicy.testReplicationWithPriority:910 Not able to clear the element from high priority list
  TestNameNodeMetrics.testStaleNodes:175 Bad value for metric StaleDataNodes expected:<2> but was:<0>
  TestDataNodeVolumeFailure.testUnderReplicationAfterVolFailure:229 There is no under replicated block after volume failure
  TestIncrementalBrVariations.testDataNodeDoesNotSplitReports:220 Bad value for metric BlockReceivedAndDeletedOps expected:<15> but was:<14>
  TestDataTransferKeepalive.testSlowReader:151->assertXceiverCount:199 Expected 0 xceivers, found 1
  TestDatanodeBlockScanner.testDuplicateScans:479 There should not be duplicate scan expected:<2488810873> but was:<2488820880>
  TestGetBlocks.testReadSelectNonStaleDatanode:182 expected:<host[5].foo.com> but was:<host[2].foo.com>

Tests in error: 
  TestDecommission.testHostsFile:525->testHostsFile:543 » Bind Port in use: 0.0....
  TestNodeCount.testNodeCount:107->checkTimeout:190->checkTimeout:196 Timeout Ti...
  TestBlocksWithNotEnoughRacks.testReduceReplFactorDueToRejoinRespectsRackPolicy:382 » Timeout
  TestClusterId.testFormatWithForce:168 »  test timed out after 450000 milliseco...
  TestClusterId.testFormatWithForceAndClusterId:194 »  test timed out after 4500...
  TestClusterId.testFormatWithNonInteractiveAndForce:320 »  test timed out after...
  TestIncrementalBrVariations.testNnLearnsNewStorages:263 » NullPointer
  TestBlockReportLoadBalancing.TestBRTrackingService_02:154 » BRLoadBalancing Wo...
  TestBlockReportLoadBalancing.TestCommandLine:232 » BRLoadBalancing Work (10000...
  TestBlockReportLoadBalancing.TestClusterWithOutDataNodes:281 » BRLoadBalancing
  TestWebHDFS.testNamenodeRestart:219->Object.wait:503->Object.wait:-2 »  test t...
  TestWebHDFS.testLargeFile:89->largeFileTest:138->verifySeek:178 » IO Unexpecte...
```

The errors are largely timeouts, so not "real" errors... but still have to be looked into, of course.

**Comment by bcleenders** [comment]
Latest test results: https://gist.github.com/bcleenders/cecef5e8a6f996a6ee96b936f46bb01d

**Comment by bcleenders** [comment]
Pulled changes from hops/develop, to make it easier to compare/merge the two.

```
Tests that failed during the tests:
Failed tests: 
  TestDecommission.testDecommission:355->testDecommission:405 null
  TestComputeInvalidateWork.testCompInvalidate:75 expected:<3000> but was:<0>
  TestReplicationPolicy.testChooseTarget6:480 expected:<1> but was:<2>
  TestReplicationPolicy.testChooseTargetWithStaleNodes:599 expected:<127.0.0.1:48578[DISK]DS-79722039-b433-42ed-927b-8387bfc2313a:NORMAL> but was:<127.0.0.1:54987[DISK]DS-96d15d8c-0bf7-4254-8a91-cc0d3e00bdb4:NORMAL>
  TestReplicationPolicy.testChooseTargetWithHalfStaleNodes:638 null
  TestReplicationPolicy.testChooseTargetWithMoreThanHalfStaleNodes:696 expected:<0> but was:<2>
  TestReplicationPolicy.testReplicationWithPriority:910 Not able to clear the element from high priority list
  TestNameNodeMetrics.testStaleNodes:175 Bad value for metric StaleDataNodes expected:<2> but was:<0>
  TestListCorruptFileBlocks.testlistCorruptFileBlocksDFS:449 Test resulted in an unexpected exit
  TestDataNodeVolumeFailure.testUnderReplicationAfterVolFailure:229 There is no under replicated block after volume failure
  TestIncrementalBrVariations.testDataNodeDoesNotSplitReports:220 Bad value for metric BlockReceivedAndDeletedOps expected:<15> but was:<14>
  TestReplication.testReplication:263->runReplication:250 Test resulted in an unexpected exit
  TestDataTransferKeepalive.testSlowReader:151->assertXceiverCount:199 Expected 0 xceivers, found 1
  TestDatanodeBlockScanner.testDuplicateScans:479 There should not be duplicate scan expected:<11894401768> but was:<11894411773>
  TestGetBlocks.testReadSelectNonStaleDatanode:182 expected:<host[2].foo.com> but was:<host[5].foo.com>

Tests in error: 
  TestNodeCount.testNodeCount:107->checkTimeout:190->checkTimeout:196 Timeout Ti...
  TestBlocksWithNotEnoughRacks.testReduceReplFactorDueToRejoinRespectsRackPolicy:382 » Timeout
  TestClusterId.testFormatWithNonInteractiveAndForce:320 »  test timed out after...
  TestClusterId.testFormatWithoutForceEnterYes:355 »  test timed out after 30000...
  TestClusterId.testFormatClusterIdOption:89 »  test timed out after 300000 mill...
  TestClusterId.testFormat:118 »  test timed out after 300000 milliseconds
  TestIncrementalBrVariations.testNnLearnsNewStorages:263 » NullPointer
  TestBlockReportLoadBalancing.TestBRTrackingService_02:154 » BRLoadBalancing Wo...
  TestBlockReportLoadBalancing.TestCommandLine:232 » BRLoadBalancing Work (10000...
  TestBlockReportLoadBalancing.TestClusterWithOutDataNodes:281 » BRLoadBalancing
  TestWebHDFS.testNamenodeRestart:219->Object.getClass:-2 »  test timed out afte...
  TestWebHDFS.testLargeFile:89->largeFileTest:127 » Remote File /test/largeFile/...
  TestLease.testLease:323 » Remote [ByINodeId] Trying to access storage while it...
  TestDistributedFileSystem.testAllWithDualPort » Remote -1
	at java.util.ArrayL...
  TestDistributedFileSystem.testGetFileBlockStorageLocationsBatching:631 » Remote
  TestDistributedFileSystem.testGetFileBlockStorageLocationsError:677 » IO io.ho...
  TestDistributedFileSystem.testCreateWithCustomChecksum:723 » IO io.hops.except...
  TestDistributedFileSystem.testDFSClose:109 » IO io.hops.exception.StorageExcep...
  TestDistributedFileSystem.testDFSSeekExceptions:136 » IO io.hops.exception.Sto...
  TestDistributedFileSystem.testDFSClient:178 » IO io.hops.exception.StorageExce...
  TestDistributedFileSystem.testFileSystemCloseAll:80 » IO io.hops.exception.Sto...
  TestDistributedFileSystem.testStatistics:331 » IO io.hops.exception.StorageExc...
  TestDistributedFileSystem.testFileChecksum:440 » IO io.hops.exception.StorageE...
```

Largely caused by: java.io.IOException: io.hops.exception.StorageException: com.mysql.clusterj.ClusterJUserException: A transaction must not be active for method begin.

**Comment by jimdowling** [comment]
@bcleenders - can you give me details on the failed tests. @maismail has been busy with two papers and hasn't merged. We are going to reformat the data center machines with ZFS next week, so i would like to get this feature in (all the way to hopsworks) soon after that.

**Pull request closed without merging**
