### PR TITLE
Heterogeneous storage

### PR DESCRIPTION
**Pull request by bcleenders**
Don't merge this PR just yet; it's just to track the changes that I hope we'll implement shortly.

Before merging, we have to add https://github.com/bcleenders/hops/pull/7 as well (it has many bugfixes and features for this branch). Also, https://github.com/bcleenders/hops/pull/15 should be included, because it persists the storage policy in the database.

---
This change is [Reviewable](https://reviewable.io/reviews/hopshadoop/hops/270)

### CODE REVIEW

**Comment by bcleenders** [comment]
If anyone wants to review, that'd be nice!

Next week I'm gonna do a bit more debugging (there are some odd errors remaining, some missing testcases and some incorrect testcases). However, any comments are already welcome :)

**Comment by jimdowling** [comment]
@maismail  - can you start ?

**Comment by bcleenders** [comment]
So I fixed some TODOs/bugs.

Running the hdfs test suite has the following errors:

```
Results :

Failed tests: 
  TestDFSClientRetries.testNamenodeRestart:810->namenodeRestartTest:957->assertEmpty:1035 There are 1 exception(s):
  Exception 0: java.lang.RuntimeException: io.hops.exception.StorageException: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1245)
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1238)
	at org.apache.hadoop.security.UserGroupInformation.createRemoteUser(UserGroupInformation.java:1109)
	at org.apache.hadoop.security.UserGroupInformation.createUserForTesting(UserGroupInformation.java:1260)
	at org.apache.hadoop.hdfs.TestDFSClientRetries.createFsWithDifferentUsername(TestDFSClientRetries.java:1044)
	at org.apache.hadoop.hdfs.TestDFSClientRetries.access$100(TestDFSClientRetries.java:97)
	at org.apache.hadoop.hdfs.TestDFSClientRetries$5.run(TestDFSClientRetries.java:900)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.hops.exception.StorageException: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at io.hops.metadata.ndb.mysqlserver.HopsSQLExceptionHelper.wrap(HopsSQLExceptionHelper.java:31)
	at io.hops.metadata.ndb.mysqlserver.MySQLQueryHelper.execute(MySQLQueryHelper.java:143)
	at io.hops.metadata.ndb.dalimpl.hdfs.UserClusterj.addUser(UserClusterj.java:76)
	at io.hops.metadata.ndb.dalimpl.hdfs.UserClusterj.addUser(UserClusterj.java:32)
	at io.hops.security.UsersGroups$4.performTask(UsersGroups.java:292)
	at io.hops.transaction.handler.LightWeightRequestHandler.execute(LightWeightRequestHandler.java:50)
	at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:52)
	at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:47)
	at io.hops.security.UsersGroups.addUserToGroups(UsersGroups.java:286)
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1243)
	... 7 more
Caused by: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MySQLQueryHelper.execute(MySQLQueryHelper.java:141)
	... 15 more

  TestComputeInvalidateWork.testCompInvalidate:75 expected:<3000> but was:<0>
  TestNameNodeMetrics.testStaleNodes:175 Bad value for metric StaleDataNodes expected:<2> but was:<0>
  TestDataNodeVolumeFailure.testUnderReplicationAfterVolFailure:229 There is no under replicated block after volume failure
  TestWebHDFS.testNamenodeRestart:219 There are 1 exception(s):
  Exception 0: java.lang.RuntimeException: io.hops.exception.StorageException: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1245)
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1238)
	at org.apache.hadoop.security.UserGroupInformation.createRemoteUser(UserGroupInformation.java:1109)
	at org.apache.hadoop.security.UserGroupInformation.createUserForTesting(UserGroupInformation.java:1260)
	at org.apache.hadoop.hdfs.TestDFSClientRetries.createFsWithDifferentUsername(TestDFSClientRetries.java:1044)
	at org.apache.hadoop.hdfs.TestDFSClientRetries.access$100(TestDFSClientRetries.java:97)
	at org.apache.hadoop.hdfs.TestDFSClientRetries$6.run(TestDFSClientRetries.java:923)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.hops.exception.StorageException: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at io.hops.metadata.ndb.mysqlserver.HopsSQLExceptionHelper.wrap(HopsSQLExceptionHelper.java:31)
	at io.hops.metadata.ndb.mysqlserver.MySQLQueryHelper.execute(MySQLQueryHelper.java:143)
	at io.hops.metadata.ndb.dalimpl.hdfs.UserClusterj.addUser(UserClusterj.java:76)
	at io.hops.metadata.ndb.dalimpl.hdfs.UserClusterj.addUser(UserClusterj.java:32)
	at io.hops.security.UsersGroups$4.performTask(UsersGroups.java:292)
	at io.hops.transaction.handler.LightWeightRequestHandler.execute(LightWeightRequestHandler.java:50)
	at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:52)
	at io.hops.transaction.handler.RequestHandler.handle(RequestHandler.java:47)
	at io.hops.security.UsersGroups.addUserToGroups(UsersGroups.java:286)
	at org.apache.hadoop.security.UserGroupInformation.createHopsUser(UserGroupInformation.java:1243)
	... 7 more
Caused by: java.sql.SQLException: Got error 4350 'Transaction already aborted' from NDBCLUSTER
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3609)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3541)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2002)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2163)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2624)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2127)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2427)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2345)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2330)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at io.hops.metadata.ndb.mysqlserver.MySQLQueryHelper.execute(MySQLQueryHelper.java:141)
	... 15 more

  TestDataTransferKeepalive.testSlowReader:151->assertXceiverCount:199 Expected 0 xceivers, found 1
  TestDatanodeBlockScanner.testDuplicateScans:479 There should not be duplicate scan expected:<1451995904> but was:<1452005922>
  TestGetBlocks.testReadSelectNonStaleDatanode:189 expected:<host[4].foo.com> but was:<host[2].foo.com>
```

**Comment by bcleenders** [comment]
Can be ignored; everything is already in branch develop-heterogeneous-storage

(see https://github.com/hopshadoop/hops/pull/271 )

**Pull request closed without merging**
