### PR TITLE
modifications to use the lastest version of the streaming library.

### PR DESCRIPTION
**Pull request by berthoug**
Modification to use the lastest version of the streaming library. This is a result of hopshadoop/hops-metadata-dal-impl-ndb#28

### CODE REVIEW

**Comment by jimdowling** [comment]
Is there a config file with this library? If yes, where is it in the project.

**Comment by jimdowling** [comment]
Last == latest ??

**Comment by berthoug** [comment]
Jenkins retest this please

**Comment by berthoug** [comment]
The library config files are with the library in Hops-metadat-dal-impl-ndb. I updated the README.md to indicate that they should be copied to hops-hadoop-chef the same way as we do for the schema.

**Pull request merged**
