### PR TITLE
[HOPS-11] Fix permission issue with writing to Cgroups device subsystem

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by robzor92** [comment]
2 tests broken, will look at it

**Comment by robzor92** [comment]
please rerun tests

**Comment by jimdowling** [comment]
Jenkins test this please.

**Comment by jimdowling** [comment]
Merging this - it only affects GPU-YARN.

**Pull request merged**
