### PR TITLE
[HOPS-99] Add makeQualified method to HdfsFileStatus and HdfsLocatedF…

### PR DESCRIPTION
**Pull request by SirOibaf**
…ileStatus
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-99

### CODE REVIEW

**Comment by SirOibaf** [comment]
The patch compiles locally and works with Hive. @maismail, when you have time, could you please take a look at the PR to see that everything is more or less ok?

@berthoug we will run the tests when HOPS-96 is done.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Could you add the link the to Jira in your pull request descriptions?

**Comment by maismail** [comment]
The changes looks okay to me.

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
There is this error that need to be solved when trying to run the test on jenkins:
`[ERROR] /home/jenkins/workspace/hops-pull-new/hadoop-hdfs-project/hadoop-hdfs/src/test/java/org/apache/hadoop/hdfs/web/TestJsonUtil.java:[38,25] no suitable constructor found for Path(org.apache.hadoop.fs.Path)
    constructor org.apache.hadoop.fs.Path.Path(java.lang.String) is not applicable
      (argument mismatch; org.apache.hadoop.fs.Path cannot be converted to java.lang.String)
    constructor org.apache.hadoop.fs.Path.Path(java.net.URI) is not applicable
      (argument mismatch; org.apache.hadoop.fs.Path cannot be converted to java.net.URI)
`

**Comment by berthoug** [comment]
also have a look at TestLambdaTestUtils and TestRMAdminService

**Comment by berthoug** [comment]
Jenkins test this please.

**Pull request merged**
