### PR TITLE
YARN-2107

### PR DESCRIPTION
**Pull request by giannokostas**

### CODE REVIEW

**Comment by berthoug** [comment]
TestApplicationHistoryClientService is failing

**Comment by berthoug** [comment]
YARN-2022 seems to move LeveldbTimelineStore from _org.apache.hadoop.yarn.server.applicationhistoryservice.timeline_ to _org.apache.hadoop.yarn.server.timeline_ but this is not done here.
https://issues.apache.org/jira/secure/attachment/12646997/YARN-2107.1.txt

**Comment by giannokostas** [comment]
YARN-2107 
All the tests pass...

**Comment by berthoug** [comment]
The correct correction for the problem is probably https://issues.apache.org/jira/browse/HADOOP-10588 and not to add a @Inject

**Pull request merged**
