### PR TITLE
[HOPS-1156] Fix datanode not stale variable for Multi NN

### PR DESCRIPTION
**Pull request by smkniazi**
[HOPS-1112] Fix firstBlockReport check in BlockManager for Multi NN

## Make sure there is no duplicate PR for this issue

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added and passed (for bug fixes / features)
- [x] HOPS JIRA issue has been opened for this PR
- [x] All commits have been squashed down to a single commit
- [x] The commit message has the following format: [HOPS-XXX] message

* **Post a link to the associated JIRA issue**
https://hopshadoop.atlassian.net/browse/HOPS-1156
https://hopshadoop.atlassian.net/browse/HOPS-1112

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
This seems to be breaking TestBlockManager
And it needs conflicts resolving.

**Comment by smkniazi** [comment]
https://bbc1.sics.se/jenkins/job/dist-test/33/

Flaky test  org.apache.hadoop.hdfs.server.datanode.TestNNHandlesBlockReportPerStorage.blockReport_09

**Comment by berthoug** [comment]
Jenkins test this please.

**Comment by berthoug** [comment]
Jenkins test this please.

**Pull request merged**
