### PR TITLE
[HOPS-49] Making HopsFS Java 8 Style Compliant

### PR DESCRIPTION
**Pull request by augustbonds**

### CODE REVIEW

**Comment by maismail** [comment]
Ok to test.

**Comment by maismail** [comment]
Jenkins retest this please.

**Comment by augustbonds** [comment]
Tried a few of these tests on my machine and they pass. Can this be retested?

**Comment by augustbonds** [comment]
Jenkins retest this please.

**Comment by maismail** [comment]
Jenkins retest this please.

**Comment by berthoug** [comment]
Jenkins retest this please.

**Comment by berthoug** [comment]
Jenkins retest this please.

**Pull request merged**
